version: "3"
services:
  nginx:
    container_name: nginx
    #restart : always
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - ./tools:/usr/share/html
    ports:
      - "443:443"
    networks:
      - mynetwork

  wordpress:
    container_name : wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    #restart : always
    working_dir: /usr/share/html/
    volumes:
      - ./tools:/usr/share/html
    ports:
      - "9000:9000"
    networks:
      - mynetwork
  mariadb:
    container_name : mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    #volumes:
    #  - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
#volumes:
#  tools:
