version: "3.5"
services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart : always
    volumes:
      - /home/bperraud/data/wordpress:/usr/share/html
    ports:
      - "443:443"
    networks:
      - mynetwork
  wordpress:
    container_name : wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart : always
    working_dir: /usr/share/html/
    volumes:
      - /home/bperraud/data/wordpress:/usr/share/html
    ports:
      - "9000:9000"
    networks:
      - mynetwork
  mariadb:
    container_name : mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart : always
    working_dir: /var/lib/mysql
    volumes:
      - /home/bperraud/data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
