version: "3"
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - mynetwork
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - mynetwork
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
