version: "3.5"
services:
  nginx:
    container_name: nginx
    restart : always
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp:/usr/share/html
    ports:
      - "443:443"
    networks:
      - mynetwork

  wordpress:
    container_name : wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart : always
    working_dir: /usr/share/html/
    volumes:
      - wp:/usr/share/html
    ports:
      - "9000:9000"
    networks:
      - mynetwork
  mariadb:
    container_name : mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart : always
    working_dir: /var/lib/mysql
    volumes:
      - maria:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/bperraud/data/wordpress
  maria:
    driver: local
    name: maria
    driver_opts:
      type: none
      o: bind
      device: /home/bperraud/data/mariadb
