CREATE DATABASE WP_DB;
CREATE USER 'WP_DB_USER'@'%' IDENTIFIED BY 'WP_DB_PASSWORD';
GRANT ALL PRIVILEGES ON WP_DB.* TO 'WP_DB_USER'@'%' IDENTIFIED BY 'WP_DB_PASSWORD';
FLUSH PRIVILEGES;

ALTER USER 'root'@'%' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
